swagger: "2.0"

info:
  title: busroutes-visualizer
  version: 0.0.1

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  authorization_header:
    description: Аутентификационный токен. Формат "Bearer токен"
    type: apiKey
    name: Authorization
    in: header

definitions:
  permission:
    description: Права пользователя на определенные действия
    properties:
      user_id:
        description: Идентификаторы пользователей
        type: integer
        example: 1
      actions:
        description: Действия, разрешенные пользователю
        type: array
        items:
          type: string
        example: [action1, action2]

tags:
  - name: graphs
    description: Graphs routes
  - name: permissions
    description: Permissions routes

paths:
  /api/v1/permissions:
    get:
      summary: Получение прав пользователей на определенные действия
      tags:
        - permissions
      security:
        - authorization_header: []
      description: |
        Для пользователей с типом:
        `admin`
        `service`
        Требуется подписка.
      parameters:
        - name: user_ids
          description: Идентификаторы пользователей
          in: query
          type: array
          items:
            type: integer
        - name: actions
          description: Действия, разрешенные пользователю
          in: query
          type: array
          items:
            type: string
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/permission"
        "400":
          description: Bad request
        "500":
          description: Internal server error

  /api/v1/graphs:
    get:
      summary: Получение графа маршрутов автобуса
      produces:
        - image/png
      tags:
        - graphs
      security:
        - authorization_header: []
      description: |
        Для пользователей с типом:
        `admin`
        `service`
        Требуется подписка.
      parameters:
        - name: city
          description: Город
          in: query
          type: string
          required: true
        - name: bus
          description: Номер автобуса
          in: query
          type: string
          required: true
      responses:
        "200":
          description: Success
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
