swagger: "2.0"

info:
  title: busroutes-visualizer
  version: 0.0.1

schemes:
  - http

consumes:
  - application/json

produces:
  - application/json

securityDefinitions:
  authorization_header:
    description: Аутентификационный токен. Формат "Bearer токен"
    type: apiKey
    name: Authorization
    in: header

definitions:
  RoutePoint:
    properties:
      step:
        description: Порядковый номер остановки по маршруту автобуса
        type: integer
        example: 1
      address:
        description: Адрес остановки
        type: string
        example: ул. Улица, 1
  RouteDetailed:
    properties:
      city:
        description: Название города
        type: string
        example: Москва
      num:
        description: Номер автобуса
        type: string
        example: "1"
      points:
        description: Точки остановок
        type: array
        items:
          $ref: "#/definitions/RoutePoint"

paths:
  /api/v1/graphs:
    get:
      summary: Получение графа маршрутов автобуса
      tags:
        - graphs
      security:
        - authorization_header: []
      description: |
        Для пользователей с типом:
        `admin`
        `service`
      parameters:
        - name: city
          description: Город
          in: query
          type: string
          required: true
        - name: bus
          description: Номер автобуса
          in: query
          type: string
          required: true
      responses:
        "200":
          description: Success
          schema:
            $ref: "#/definitions/RouteDetailed"
        "400":
          description: Bad request
        "401":
          description: Unauthorized
        "403":
          description: Forbidden
        "500":
          description: Internal server error
